### PR TITLE
fix: checked state of ToggleSwitch can be controlled by caller

### LINKED ISSUE #309: fix: value of `ToggleSwitch` should be controlled by caller
The `ToggleSwitch` component can not be controlled by the caller.
This would enable resetting the toggle programmatically, which is not possible currently.

Currently, only the `initialValue` can be set. It would be a good improvement to have complete control over it by the calling component.

### PR DESCRIPTION
**Pull request by theborakompanioni**
Fixes #309.

Small change to control the `checked` value by the parent component.
Previously a state change in the calling component was not visually displayed by the `ToggleSwitch` component.
After this change the `ToggleSwitch` will reflect the actual value correctly.

### CODE REVIEW

File: src/components/ToggleSwitch.tsx [hunk 1]
```diff
@@ -5,18 +5,18 @@ interface ToggleSwitchProps {
   label: string
   subtitle?: string
   onToggle: (isToggled: boolean) => void
```
Comment (dnlggr) [inline src/components/ToggleSwitch.tsx:7]: For consistency with the new prop, let's rename this to `isChecked`.

```suggestion
  onToggle: (isChecked: boolean) => void
```

Comment (theborakompanioni) [reply src/components/ToggleSwitch.tsx:7]: Good point! I am tempted to rename the `checked` property to `toggled`.. would that also be okay?

Comment (dnlggr) [reply src/components/ToggleSwitch.tsx:7]: Let's do `toggledOn` then? Since a switch can be toggled either way, with just `toggled` it would not be clear if it's toggled on or off.

**Review by dnlggr — APPROVED** [review]

File: src/components/ToggleSwitch.tsx (hunk 1 above)
Comment (theborakompanioni) [reply src/components/ToggleSwitch.tsx:7]: Perfect :ok_hand:
