### PR TITLE
fix: delay scheduler start/stop

### LINKED ISSUE #249: Delay starting / stopping scheduled transactions UI side
See https://github.com/joinmarket-webui/joinmarket-webui/pull/242.

To avoid users starting/stopping the service in rapid succession which can lead to problems.

### PR DESCRIPTION
**Pull request by dnlggr**
Resolves #249.

I used the same delay (2000ms) as in the Earn screen. What do you think @theborakompanioni, is that long enough?

A bit off topic, but I also renamed all API methods to refer to "Scheduler" now.

### CODE REVIEW

**Comment by theborakompanioni** [comment]
> I used the same delay (2000ms) as in the Earn screen. What do you think @theborakompanioni, is that long enough?

It seems it will sufficiently keep users from starting/stopping the scheduler in rapid succession.
However, there might still be problems if the servers actual state is not taken into account.

This is for another PR, but what do you think about taking the same approach as in the Earn screen and wait for the server to signal the successful operation, ie. https://github.com/joinmarket-webui/joinmarket-webui/blob/a95ac7a6e419f52150a608e0b66c498240361db7/src/components/Earn.jsx#L156-L177

> A bit off topic, but I also renamed all API methods to refer to "Scheduler" now.

:+1:

File: src/components/Jam.jsx [hunk 1]
```diff
@@ -157,7 +158,7 @@ export default function Jam() {
     const body = { destination_addresses: destinations }
 
     if (process.env.NODE_ENV === 'development' && useInsecureTestingSettings && !deactivateTestingToggle) {
-      body.tumbler_options = {
+      body.scheduler_options = {
```
Comment (theborakompanioni) [inline src/components/Jam.jsx:161]: Are you panning to update [your server branch](https://github.com/dnlggr/joinmarket-clientserver/tree/tumbler-rpc-options) or the [the PR](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/dd8e08ffb6ebdfe9f73307575079cd2123e51e4d/jmclient/jmclient/wallet_rpc.py#L1119) as well? Both still refer to `tumbler_options`.. would need to remember that till they are in sync again..

**Review by theborakompanioni — APPROVED** [review]

File: src/components/Jam.jsx (hunk 1 above)
Comment (dnlggr) [reply src/components/Jam.jsx:161]: Oh yeah that needs to be fixed of course!

**Comment by dnlggr** [comment]
> This is for another PR, but what do you think about taking the same approach as in the Earn screen and wait for the server to signal the successful operation, ie. 

Yeah that would definitely be great! Should we track it as an issue for the next version?

File: src/components/Jam.jsx (hunk 1 above)
Comment (dnlggr) [reply src/components/Jam.jsx:161]: Fixed. Good catch! 👏
