### PR TITLE
Fix stale fee config warning reactivity

### LINKED ISSUE #1054: stale fee-config state causes false “fee configuration missing” warnings after values are loaded/saved
issue : - 
on v2, fee config UI state can become stale after fetching or saving policy values.
In [useFeeConfigValidation.ts](app://-/index.html#), feeConfigValues was memoized without depending on config state updates, so maxFeesConfigMissing could stay true even after valid values exist.
In [jmConfigStore.ts](app://-/index.html#), nested section updates were not fully immutable, which further risks missed reactivity.

User impact:

send, earn, and sweep may keep showing fee-config error alerts incorrectly.
fee settings dialog can show outdated values until remount/refresh.

### PR DESCRIPTION
**Pull request by parrth20**
problem : 
fee-config UI state could become stale after loading/saving config values, which kept showing false “fee configuration missing” warnings.
root cause : 
`useFeeConfigValidation` memoized `feeConfigValues` without depending on config state changes.
`jmConfigStore.set` used nested mutation patterns that could miss reactivity updates.

fix
updated `/src/hooks/useFeeConfigValidation.ts` to recompute fee config values when store state changes.
updated `/src/store/jmConfigStore.ts` to perform fully immutable nested updates.

impact on user 
this keeps fee warnings in `Send`, `Earn`, and `Sweep` accurate after config fetch/save and prevents stale values in fee settings UI.

fixes #1054 
@theborakompanioni @saurabhraghuvanshii

### CODE REVIEW

**Comment by parrth20** [comment]
ping @saurabhraghuvanshii please review my this PR too! and lmk if any changes are required..!!

**Comment by saurabhraghuvanshii** [comment]
@parrth20 merge conflicts

**Comment by parrth20** [comment]
> @parrth20 merge conflicts

check i have made the required changes !

File: src/hooks/useFeeConfigValidation.ts [hunk 1]
```diff
@@ -56,7 +61,7 @@ export const useFeeConfigValidation = ({ walletFileName }: UseFeeConfigValidatio
       return true
     }
 
-    return isMaxFeesConfigMissing(feeConfigValues)
+    return feeConfigValues.max_cj_fee_abs === undefined || feeConfigValues.max_cj_fee_rel === undefined
```
Comment (theborakompanioni) [inline src/hooks/useFeeConfigValidation.ts]: If `isMaxFeesConfigMissing` is not used anymore, remove it?
I think it is a good reminder which of the fields are mandatory.

Comment (parrth20) [reply src/hooks/useFeeConfigValidation.ts]: > If `isMaxFeesConfigMissing` is not used anymore, remove it? I think it is a good reminder which of the fields are mandatory.

good point, agreed. I’ll keep isMaxFeesConfigMissing and call it here for readability, so the mandatory fields stay explicit. I’ll push that small cleanup now.

Comment (parrth20) [reply src/hooks/useFeeConfigValidation.ts]: > good point, agreed. I’ll keep isMaxFeesConfigMissing and call it here for readability, so the mandatory fields stay explicit. I’ll push that small cleanup now.

check @theborakompanioni

**Review by theborakompanioni — APPROVED** [review]
